version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconciliation_db

    ports:
      - "3307:3306"

  app:
    build: .
    container_name: reconciliation-app

    ports:
      - "9090:9090"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reconciliation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root