server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-king-aouw7aje.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_dqRJy1GArmS9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    
    