server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reconciliation_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  =security:
  user:
    name: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui.html